name: Deploy to Azure
on:
  push:
    branches:
      - main

jobs:
  infra-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deployment
        uses: azure/bicep-deploy@v1
        with:
          type: deploymentStack
          operation: create
          name: dk-test-webapp
          location: westus2
          scope: subscription
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template-file: ./src/DKershnerBackend/infra/main.bicep
          action-on-unmanage-resources: detach
          action-on-unmanage-resourcegroups: detach
          deny-settings-mode: none